#! /bin/sh

~/.config/polybar/launch.sh --forest

pgrep -x sxhkd > /dev/null || sxhkd &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
bspc config single_monocle false

bspc rule -a Google-chrome desktop='^1'
bspc rule -a WebApp-Discord5213 desktop='^5' # Actually is zapzap
bspc rule -a WebApp-YoutubeMusic1094 desktop='^6'
bspc rule -a WebApp-Calendar7623 desktop='^8'
# bspc rule -a Alacritty desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a postman desktop='^4'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#d65d0e"
bspc config normal_border_color         "#3c3836"
bspc config active_border_color         "#3c3836"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar

# Notifications
/usr/bin/dunst &

# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

sleep 4

# Apps autostart
dex ~/.local/share/applications/WebApp-Discord5213.desktop & # actually is zapzap
discord &
dex ~/.local/share/applications/WebApp-Calendar7623.desktop &
dex ~/.local/share/applications/WebApp-YoutubeMusic1094.desktop &
google-chrome-stable &
bspc desktop -f 2 &
